// ============================================
// COMPREHENSIVE AFRICAN DISHES DATABASE
// With cultural notes, origins, regions, and ingredients
// ============================================

const africanDishes = [
    // ========== NORTH AFRICA ==========
    {
        id: 101,
        name: "Tajine Marocain",
        region: "North Africa",
        country: "Morocco",
        category: "Stews & Sauces",
        price: 12.00,
        image: "images/menu/tajine.jpg",
        description: "Slow-cooked stew with meat, vegetables, and dried fruits.",
        origin: "Morocco",
        cultural_note: "The tajine (also the name of the conical cooking vessel) is the soul of Moroccan cuisine. It originated in Berber communities and represents hospitality and family gatherings.",
        history: "Dating back centuries, tajines were traditionally cooked in clay pots over open fires. The conical lid traps steam, cooking food slowly and infusing flavors.",
        ingredients: ["Beef or lamb", "Onions", "Garlic", "Turmeric", "Ginger", "Cinnamon", "Apricots", "Almonds", "Olive oil"],
        occasions: "Special celebrations, family gatherings, Friday dinners",
        prep_time: "60-90 minutes",
        vegetarian: false
    },
    {
        id: 102,
        name: "Couscous Marocain",
        region: "North Africa",
        country: "Morocco",
        category: "Rice & Grains",
        price: 10.50,
        image: "images/menu/couscous.jpg",
        description: "Fluffy semolina grains with seasoned meat and vegetables.",
        origin: "Morocco, Algeria, Tunisia",
        cultural_note: "Couscous is the national dish of the Maghreb. The word comes from the Berber 'seksu' meaning 'well rolled'. It's served at almost every celebration.",
        history: "Couscous production dates back to the 7th century. Originally made by hand rolling semolina, it's now often prepared with mechanical methods.",
        ingredients: ["Couscous", "Lamb or chicken", "Chickpeas", "Carrots", "Zucchini", "Onions", "Spices (cumin, paprika, cinnamon)"],
        occasions: "Weekly family meals, religious holidays, Friday lunch",
        prep_time: "45 minutes",
        vegetarian: false
    },
    {
        id: 103,
        name: "Zaalouk",
        region: "North Africa",
        country: "Morocco",
        category: "Appetizers",
        price: 6.50,
        image: "images/menu/zaalouk.jpg",
        description: "Roasted eggplant salad with tomatoes, garlic, and cilantro.",
        origin: "Morocco",
        cultural_note: "Often called the 'poor man's caviar', zaalouk is a humble yet delicious appetizer that appears at almost every Moroccan table.",
        history: "This dish reflects the Moroccan tradition of transforming simple ingredients into flavorful dishes. It's served at room temperature as part of meze (appetizers).",
        ingredients: ["Eggplant", "Tomatoes", "Garlic", "Cilantro", "Cumin", "Paprika", "Olive oil", "Lemon juice"],
        occasions: "Appetizer before main meals, everyday dining",
        prep_time: "30 minutes",
        vegetarian: true
    },
    {
        id: 104,
        name: "Msemen (Moroccan Pastry)",
        region: "North Africa",
        country: "Morocco",
        category: "Breads",
        price: 5.50,
        image: "images/menu/msemen.jpg",
        description: "Flaky, folded pastry bread, traditionally served with honey or savory fillings.",
        origin: "Morocco",
        cultural_note: "Msemen is a beloved breakfast and snack food in Morocco, often served with mint tea. The word means 'greased' in Arabic.",
        history: "This pastry requires skill to prepare - the dough is stretched paper-thin and folded multiple times. It's been a staple for generations.",
        ingredients: ["Flour", "Water", "Butter", "Oil", "Salt", "Honey or egg filling"],
        occasions: "Breakfast, afternoon tea, Ramadan breaking of fast",
        prep_time: "40 minutes",
        vegetarian: true
    },
    {
        id: 105,
        name: "Harira",
        region: "North Africa",
        country: "Morocco, Tunisia",
        category: "Soups",
        price: 7.00,
        image: "images/menu/harira.jpg",
        description: "Traditional soup with tomatoes, lentils, chickpeas, and warm spices.",
        origin: "Morocco, Tunisia",
        cultural_note: "Harira is the quintessential Ramadan soup. Moroccans and Tunisians break their fast with a steaming bowl of harira.",
        history: "This soup has been part of North African cuisine for centuries, evolving with regional preferences. Each family has their own recipe.",
        ingredients: ["Tomatoes", "Lentils", "Chickpeas", "Onions", "Garlic", "Turmeric", "Ginger", "Cilantro", "Parsley"],
        occasions: "Ramadan breaking of fast, cold winter days, family dinners",
        prep_time: "45 minutes",
        vegetarian: false
    },

    // ========== WEST AFRICA ==========
    {
        id: 201,
        name: "Thiéboudienne",
        region: "West Africa",
        country: "Senegal",
        category: "Rice & Grains",
        price: 13.50,
        image: "images/menu/thieboudienne.jpg",
        description: "National dish: seasoned rice cooked with fish and vegetables.",
        origin: "Senegal (Saint-Louis region)",
        cultural_note: "Thiéboudienne, meaning 'rice and fish', is Senegal's national dish and a source of national pride. It's served at celebrations and represents Senegalese hospitality.",
        history: "This dish originated in the Casamance region and gained prominence in Saint-Louis. It reflects Senegal's rich fishing heritage and colonial influences.",
        ingredients: ["Rice", "Fresh fish (grouper, snapper)", "Carrots", "Squash", "Cabbage", "Cassava", "Onions", "Tomato paste", "African locust beans"],
        occasions: "National celebrations, family gatherings, important events",
        prep_time: "90 minutes",
        vegetarian: false
    },
    {
        id: 202,
        name: "Jollof Rice",
        region: "West Africa",
        country: "Ghana, Nigeria, Senegal",
        category: "Rice & Grains",
        price: 9.50,
        image: "images/menu/jollof.jpg",
        description: "Vibrant red rice cooked in tomato base with spices.",
        origin: "West Africa (Ghana, Nigeria, Senegal)",
        cultural_note: "Jollof Rice is iconic in West African cuisine. Each country claims the best version, creating friendly 'Jollof wars'. It's a celebration staple across the region.",
        history: "This dish has roots in Senegal but has been adopted and adapted throughout West Africa, particularly in Ghana and Nigeria.",
        ingredients: ["Rice", "Tomatoes", "Onions", "Red bell peppers", "Tomato paste", "Beef or chicken stock", "Scotch bonnet peppers", "Oil"],
        occasions: "Weddings, birthdays, holidays, celebrations",
        prep_time: "45 minutes",
        vegetarian: false
    },
    {
        id: 203,
        name: "Mafé (Peanut Butter Stew)",
        region: "West Africa",
        country: "Senegal, Mali, Côte d'Ivoire",
        category: "Stews & Sauces",
        price: 11.00,
        image: "images/menu/mafe.jpg",
        description: "Creamy peanut butter stew with meat and vegetables.",
        origin: "Senegal, Mali, Côte d'Ivoire",
        cultural_note: "Mafé represents the heart of West African cooking. The peanut (groundnut) is a staple ingredient, and this rich, warming stew is comfort food.",
        history: "Peanuts arrived in Africa from South America and became integral to West African cuisine. Mafé showcases this perfectly.",
        ingredients: ["Peanut butter (natural)", "Beef or lamb", "Onions", "Garlic", "Tomato paste", "Sweet potato", "Carrots", "Cabbage", "Stock"],
        occasions: "Daily family meals, celebrations, comfort food",
        prep_time: "60 minutes",
        vegetarian: false
    },
    {
        id: 204,
        name: "Alloco (Fried Plantains)",
        region: "West Africa",
        country: "Côte d'Ivoire",
        category: "Snacks & Appetizers",
        price: 6.50,
        image: "images/menu/alloco.jpg",
        description: "Crispy fried plantain slices with spicy sauce.",
        origin: "Côte d'Ivoire",
        cultural_note: "Alloco is street food in Côte d'Ivoire and beloved throughout West Africa. It's quick, delicious, and affordable.",
        history: "This simple dish reflects the abundance of plantains in West Africa and the creativity of street food vendors.",
        ingredients: ["Plantains", "Onions", "Tomatoes", "Hot peppers", "Palm oil", "Salt"],
        occasions: "Street food, snacks, casual meals, gatherings",
        prep_time: "20 minutes",
        vegetarian: true
    },
    {
        id: 205,
        name: "Foutou (Mashed Plantain)",
        region: "West Africa",
        country: "Côte d'Ivoire, Ghana",
        category: "Side Dishes",
        price: 7.50,
        image: "images/menu/foutou.jpg",
        description: "Smooth mashed plantain served with soup or sauce.",
        origin: "Côte d'Ivoire, Ghana",
        cultural_note: "Foutou is a staple side dish in West Africa. The soft, comforting texture makes it perfect for soaking up rich sauces.",
        history: "This dish has been part of West African cuisine for centuries, prepared in slightly different ways across countries.",
        ingredients: ["Plantains", "Water", "Butter", "Salt", "Sometimes palm oil"],
        occasions: "Regular meals, served with stews and soups",
        prep_time: "30 minutes",
        vegetarian: false
    },
    {
        id: 206,
        name: "Garba (Attiéké & Grilled Fish)",
        region: "West Africa",
        country: "Côte d'Ivoire",
        category: "Main Dishes",
        price: 11.50,
        image: "images/menu/garba.jpg",
        description: "Cassava couscous served with fried or grilled fish.",
        origin: "Côte d'Ivoire",
        cultural_note: "Garba represents Ivorian coastal culture and the importance of fish in West African diet.",
        history: "Attiéké (cassava semolina) is a traditional Ivorian staple, often served with fresh fish from the Atlantic.",
        ingredients: ["Cassava", "Fresh fish (mackerel, tuna)", "Onions", "Tomatoes", "Hot peppers", "Lime", "Oil"],
        occasions: "Casual meals, beach gatherings, regular dining",
        prep_time: "40 minutes",
        vegetarian: false
    },
    {
        id: 207,
        name: "Poulet Yassa",
        region: "West Africa",
        country: "Senegal",
        category: "Main Dishes",
        price: 11.00,
        image: "images/menu/poulet-yassa.jpg",
        description: "Marinated chicken with onions, mustard, and lemon.",
        origin: "Senegal",
        cultural_note: "Yassa is a beloved Senegalese dish, often prepared at celebrations. The marinade tenderizes the chicken and adds complex flavors.",
        history: "This dish represents Senegalese culinary sophistication, combining European and African flavors.",
        ingredients: ["Chicken", "Onions", "Lemon juice", "Dijon mustard", "Garlic", "Thyme", "Olives", "Scotch bonnet peppers"],
        occasions: "Celebrations, family dinners, weekend meals",
        prep_time: "120 minutes (marinating + cooking)",
        vegetarian: false
    },

    // ========== CENTRAL AFRICA ==========
    {
        id: 301,
        name: "Ndolé",
        region: "Central Africa",
        country: "Cameroon",
        category: "Stews & Sauces",
        price: 11.50,
        image: "images/menu/ndole.jpg",
        description: "Stew with bitter leafy greens, shrimp, and groundnut sauce.",
        origin: "Cameroon",
        cultural_note: "Ndolé is Cameroon's national dish. The bitter greens are believed to have medicinal properties and are part of Cameroonian culinary identity.",
        history: "This complex dish reflects Cameroon's food traditions, blending various influences and ingredients.",
        ingredients: ["Bitter leaf greens", "Groundnut paste", "Shrimp", "Fish", "Onions", "Garlic", "Cameroon pepper", "Crayfish", "Stock"],
        occasions: "Important celebrations, family gatherings, special occasions",
        prep_time: "60 minutes",
        vegetarian: false
    },
    {
        id: 302,
        name: "Suya (Spiced Meat Skewers)",
        region: "Central Africa",
        country: "Cameroon, Nigeria",
        category: "Grilled Meats",
        price: 10.00,
        image: "images/menu/suya.jpg",
        description: "Grilled marinated meat skewers coated with spicy peanut powder.",
        origin: "Nigeria, Cameroon",
        cultural_note: "Suya is West/Central Africa's answer to kebab. It's a beloved street food and social food, often shared among friends.",
        history: "Suya vendors are a common sight in Nigerian and Cameroonian streets. The spice blend is closely guarded family secret.",
        ingredients: ["Beef or lamb", "Peanut powder", "Scotch bonnet peppers", "Ginger", "Garlic", "Paprika", "Salt", "Oil"],
        occasions: "Street food, celebrations, social gatherings, evening meals",
        prep_time: "45 minutes",
        vegetarian: false
    },
    {
        id: 303,
        name: "Moambe (Peanut Chicken)",
        region: "Central Africa",
        country: "Democratic Republic of Congo, Congo",
        category: "Stews & Sauces",
        price: 11.00,
        image: "images/menu/moambe.jpg",
        description: "Chicken in thick peanut sauce with vegetables.",
        origin: "Democratic Republic of Congo",
        cultural_note: "Moambe represents Congolese culinary heritage. The dish is hearty and deeply flavorful, perfect for sharing family meals.",
        history: "This dish has been part of Congolese cuisine for generations, adapted from ancient cooking traditions.",
        ingredients: ["Chicken", "Peanut butter", "Onions", "Garlic", "Tomatoes", "Carrots", "Palm oil", "Stock", "Hot peppers"],
        occasions: "Family dinners, celebrations, comfort food",
        prep_time: "60 minutes",
        vegetarian: false
    },

    // ========== EAST AFRICA ==========
    {
        id: 401,
        name: "Doro Wat",
        region: "East Africa",
        country: "Ethiopia",
        category: "Stews & Sauces",
        price: 12.00,
        image: "images/menu/doro-wat.jpg",
        description: "Spiced chicken stew served on injera bread.",
        origin: "Ethiopia",
        cultural_note: "Doro Wat is an Ethiopian celebration dish, traditionally prepared for holidays and special occasions. The complex spices reflect Ethiopian culinary sophistication.",
        history: "This dish dates back centuries in Ethiopian cuisine. The berbere spice blend is the soul of the dish.",
        ingredients: ["Chicken", "Onions", "Garlic", "Ginger", "Berbere spice", "Fenugreek", "Cardamom", "Black pepper", "Oil", "Stock"],
        occasions: "Holidays, celebrations, religious observances, special dinners",
        prep_time: "90 minutes",
        vegetarian: false
    },
    {
        id: 402,
        name: "Injera",
        region: "East Africa",
        country: "Ethiopia, Eritrea",
        category: "Breads",
        price: 6.00,
        image: "images/menu/injera.jpg",
        description: "Spongy fermented flatbread made from teff flour.",
        origin: "Ethiopia, Eritrea",
        cultural_note: "Injera is more than bread in Ethiopian culture - it's plate, utensil, and staple carbohydrate. It's fundamental to Ethiopian identity.",
        history: "Made from teff grain (native to Ethiopia), injera dates back centuries. The fermentation process develops its characteristic sour taste.",
        ingredients: ["Teff flour", "Water", "Salt", "Sourdough starter"],
        occasions: "Every meal in Ethiopian cuisine, daily dining",
        prep_time: "3-5 days (fermentation)",
        vegetarian: true
    },
    {
        id: 403,
        name: "Ugali",
        region: "East Africa",
        country: "Kenya, Tanzania, Uganda",
        category: "Side Dishes",
        price: 5.50,
        image: "images/menu/ugali.jpg",
        description: "Cornmeal staple served with beans or stewed meat.",
        origin: "East Africa",
        cultural_note: "Ugali is the comfort food of East Africa - filling, affordable, and versatile. It's eaten daily by millions.",
        history: "Corn arrived in Africa through trade, and East Africans quickly integrated it into their diet. Ugali became essential.",
        ingredients: ["Cornmeal", "Water", "Salt", "Butter"],
        occasions: "Daily meals, served with vegetables, beans, or meat",
        prep_time: "20 minutes",
        vegetarian: true
    },
    {
        id: 404,
        name: "Nyama Choma (Grilled Meat)",
        region: "East Africa",
        country: "Kenya",
        category: "Grilled Meats",
        price: 14.00,
        image: "images/menu/nyama-choma.jpg",
        description: "Grilled seasoned beef served with ugali and vegetables.",
        origin: "Kenya",
        cultural_note: "Nyama Choma is a Kenyan social tradition. It brings people together and represents joy and celebration.",
        history: "This simple grilled meat dish has become iconic in Kenyan culture, often found at roadside restaurants and family gatherings.",
        ingredients: ["Beef sirloin", "Onions", "Tomatoes", "Hot peppers", "Lemon juice", "Salt", "Cumin"],
        occasions: "Casual gatherings, celebrations, social meals",
        prep_time: "45 minutes",
        vegetarian: false
    },

    // ========== SOUTHERN AFRICA & ISLANDS ==========
    {
        id: 501,
        name: "Bobotie",
        region: "Southern Africa",
        country: "South Africa",
        category: "Main Dishes",
        price: 12.00,
        image: "images/menu/bobotie.jpg",
        description: "Curried mince topped with egg custard, baked until golden.",
        origin: "South Africa",
        cultural_note: "Bobotie represents South African culinary fusion, blending Cape Malay and colonial influences. It's an iconic South African comfort dish.",
        history: "This dish originated when Cape Malay slaves brought their spices and cooking techniques to South Africa, creating unique fusion cuisine.",
        ingredients: ["Ground beef", "Onions", "Curry powder", "Bread soaked in milk", "Eggs", "Raisins", "Almonds", "Chutney"],
        occasions: "Family dinners, celebrations, special occasions",
        prep_time: "60 minutes",
        vegetarian: false
    },
    {
        id: 502,
        name: "Ravitoto",
        region: "Southern Africa & Islands",
        country: "Madagascar",
        category: "Main Dishes",
        price: 11.50,
        image: "images/menu/ravitoto.jpg",
        description: "Mashed cassava leaves with pork, a national treasure.",
        origin: "Madagascar",
        cultural_note: "Ravitoto is the unofficial national dish of Madagascar. It represents Malagasy tradition and the importance of pork in their culture.",
        history: "This dish has been central to Malagasy cuisine for centuries, adapting through colonial periods while maintaining its core identity.",
        ingredients: ["Cassava leaves", "Pork", "Onions", "Garlic", "Stock", "Coconut milk"],
        occasions: "Special celebrations, important meals, cultural events",
        prep_time: "90 minutes",
        vegetarian: false
    },
    {
        id: 503,
        name: "Romazava",
        region: "Southern Africa & Islands",
        country: "Madagascar",
        category: "Stews & Sauces",
        price: 12.50,
        image: "images/menu/romazava.jpg",
        description: "Beef stew with greens, tomatoes, and aromatic spices.",
        origin: "Madagascar",
        cultural_note: "Romazava is a flavorful Malagasy dish that reflects the island's culinary traditions and access to fresh herbs and vegetables.",
        history: "This stew showcases Madagascar's unique position as an island with distinct culinary traditions separate from mainland Africa.",
        ingredients: ["Beef", "Leafy greens", "Tomatoes", "Onions", "Garlic", "Fresh herbs", "Stock"],
        occasions: "Regular meals, family gatherings, casual dinners",
        prep_time: "75 minutes",
        vegetarian: false
    },
];

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = africanDishes;
}
